### ISSUE TITLE
Ore Regen.

### ISSUE THREAD

**Issue by VoidGuardian** [ChampionAsh5357/Custom-Ideas#5]
Simple idea that I will just throw a bunch of ideas and options out there so you have a lot of option. 

make it so that ores regenerate after being mined. Similar those old mods where after the block was mined it would be replaced with a new block that would randomly turn back into the original ore. You could make it so that all ores do this, or make it so there are random large clusters of the ore so spread out that when you find one you end up building a base near it because of how useful it is. If it is possible they could have a chance to break after repeated use. If all of that is too much making a craftable ore block that regenerates so you can create dedicated mining sources in your base. crafting recipe could be something like a nether star, a potion of regen, a block of stone and 6 blocks of iron to give 1 iron regen ore. (nether star may be going to far, maybe just 2 potions of regen.) Maybe you could make how fast the ore regens configurable, but that is probably too much to ask for this already large idea. so you can set it to whatever you want.

**Comment by VoidGuardian** [comment]
Hope the idea is not to difficult to implement.

**Comment by VoidGuardian** [comment]
also, if you ever need help with texture art I am a texture artist. in fact a while ago I was working with someone on a huge mod project before they had problems in life come up and had to leave the project.  So I have a ton of unused texture art I could give you, or make more, I understand if you can do your own art, just an offer because I think it's awesome you are making a mod with a ton of small ideas from the public and I would like to help if I can.

**Comment by ChampionAsh5357** [comment]
That sounds awesome! If you want to send me the unused textures or remake the ones already in the game, go ahead. Anyone is welcome to work on the mod since I tried to make it more for the people with the people. For the ore regeneration, I added the ability to turn it on and off and change the probability of breaking. If you would still like me to add the infinite craftable ore block, let me know in the next few days.

**Comment by VoidGuardian** [comment]
An infinite craftable ore variant that works with the ore regen on or off would be a good addition in general. I always say variety is key. Also do you have a discord or messenger I could reach you at? Or an e-mail I could send the files too?

**Comment by ChampionAsh5357** [comment]
Yeah, my discord is the username with #5519. I don't really use anything else.
