### ISSUE TITLE
village guards

### ISSUE THREAD

**Issue by Spongebobfan907** [ChampionAsh5357/Custom-Ideas#8]
Are you accepting ideas for custom mobs?

**Comment by ChampionAsh5357** [comment]
I accept any idea you got.

**Comment by Spongebobfan907** [comment]
can you add barracks to villages which have 5 villager guards/soldiers

**Comment by ChampionAsh5357** [comment]
Sure

**Comment by Spongebobfan907** [comment]
can you also make it so you can trade with them?
![trade](https://user-images.githubusercontent.com/41807935/55837367-2a9b1180-5aef-11e9-8d9d-12093e0fbc04.png)

**Comment by ChampionAsh5357** [comment]
Sure

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
